apiVersion: v1
kind: Service
metadata:
  name: node-app-service
spec:
  selector:
    app: app-test
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 8080
      nodePort: 31123